# Generated by Django 5.0.2 on 2024-02-16 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=30, unique=True)),
                ("artist", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("pop_music", "Pop Music"),
                            ("jazz_music", "Jazz Music"),
                            ("r&b_music", "R&B Music"),
                            ("rock_music", "Rock Music"),
                            ("country_music", "Country Music"),
                            ("dance_music", "Dance Music"),
                            ("hip_hop_music", "Hip Hop Music"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_URL", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_auth.profile",
                    ),
                ),
            ],
        ),
    ]
