# Generated by Django 5.0.2 on 2024-02-24 08:01

import django.core.validators
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Username must be at least 3 chars long!"
                            ),
                            profiles.validators.validate_names,
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Age requirement: 21 years and above.",
                        validators=[django.core.validators.MinValueValidator(21)],
                    ),
                ),
                ("password", models.TextField(max_length=20)),
                ("first_name", models.CharField(blank=True, max_length=25, null=True)),
                ("last_name", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
