# Generated by Django 5.0.2 on 2024-02-19 16:50

import django.core.validators
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    validators.validate_names,
                ],
            ),
        ),
    ]
