# Generated by Django 5.0.2 on 2024-02-20 12:44

import django.core.validators
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            validators.validate_names,
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
